//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUKT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUKT()
        {
            this.VRSTICA = new HashSet<VRSTICA>();
        }
    
        public string P_KODA { get; set; }
        public string P_OPIS { get; set; }
        public Nullable<System.DateTime> P_DATUM { get; set; }
        public Nullable<short> P_ZALOGA { get; set; }
        public Nullable<short> P_MIN { get; set; }
        public Nullable<decimal> P_CENA { get; set; }
        public Nullable<double> P_POPUST { get; set; }
        public Nullable<int> D_KODA { get; set; }
    
        public virtual DOBAVITELJ DOBAVITELJ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VRSTICA> VRSTICA { get; set; }
    }
}
