//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App1
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRSTICA
    {
        public int RAČ_ID { get; set; }
        public short VRS_ŠT { get; set; }
        public string P_KODA { get; set; }
        public Nullable<double> VRS_KOS { get; set; }
        public Nullable<decimal> VRS_CENA { get; set; }
    
        public virtual PRODUKT PRODUKT { get; set; }
        public virtual RAČUN RAČUN { get; set; }
    }
}
